name: Auto Merge Main to Production

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: production
          base: production
          title: 'Auto PR: Main to Production'
          body: 'Automated PR from main to production'
          labels: 'automated-pr'
