name: Auto Merge Main to Production

on:
  push:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: Auto merge main to production
          title: Auto merge main to production
          body: |
            Automatic PR to merge main into production
          branch: auto-merge-main-to-production
          base: production
          delete-branch: true
