name: Main to Production

on:
  push:
    branches:
      - main

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Create a new branch from main
          git checkout -b temp-branch
          
          # Push the branch
          git push origin temp-branch
          
          # Create PR using GitHub CLI
          gh pr create \
            --base Production \
            --head temp-branch \
            --title "Sync: Main to Production" \
            --body "Automated PR to sync Production with main branch"
